### PR TITLE
fix eda notebook linting

### LINKED ISSUE #13: fixing linting problems
I added linting to this project, there are some issues that need fixing:

```
==================== Running: flake8 ====================
==================== Running: black --check . ====================
No Python files are present to be formatted. Nothing to do 😴
==================== Running: nbqa flake8 . ====================
course-material/exploratory-data-analysis-with-sql/absenteeism-dataset.md:cell_1:4:1: E722 do not use bare 'except'
course-material/exploratory-data-analysis-with-sql/absenteeism-dataset.md:cell_2:5:80: E501 line too long (99 > 79 characters)
course-material/exploratory-data-analysis-with-sql/absenteeism-dataset.md:cell_2:14:80: E501 line too long (82 > 79 characters)
course-material/intro-to-sql/making-your-first-query.md:cell_1:4:1: E722 do not use bare 'except'
course-material/intro-to-sql/making-your-first-query.md:cell_2:1:1: E265 block comment should start with '# '
course-material/intro-to-sql/making-your-first-query.md:cell_2:3:1: E265 block comment should start with '# '
The following command failed: nbqa flake8 .\nTo fix it: Install nbqa jupytext and run: pkgmt format
Error linting
```

### LINKED ISSUE #15: Fix linting issue - making your first query
Hi @jpjon 

A new github action was setup to check for linting issues. Can you please open a new pr with the content of your "making a first query" file, add a test commit and push to trigger the linting action, and check for any errors you are getting when building the docs

For example, for the "except" issue it is raising, one fix is to add 

In this case it is worth asking whether we want to keep the try-except clause for an installation 

```python
try:
    %pip install jupysql --upgrade duckdb-engine pandas --quiet
    print("Success")
except Exception as e:
    print(f"Eetry installing. Error {e}")
```

I am leaning towards no

### PR DESCRIPTION
**Pull request by lfunderburk**
Fixes #13

### CODE REVIEW

**Comment by lfunderburk** [comment]
Hi Eduardo, 

How can we fix 

`The following command failed: nbqa flake8 .\nTo fix it: Install nbqa jupytext and run: pkgmt format`

**Comment by edublancas** [comment]
so the full error trace is:

```
No Python files are present to be formatted. Nothing to do 😴
course-material/intro-to-sql/making-your-first-query.md:cell_1:4:1: E722 do not use bare 'except'
Error linting
==================== Running: flake8 ====================
==================== Running: black --check . ====================
==================== Running: nbqa flake8 . ====================
The following command failed: nbqa flake8 .\nTo fix it: Install nbqa jupytext and run: pkgmt format
```

the actual error is:

```
course-material/intro-to-sql/making-your-first-query.md:cell_1:4:1: E722 do not use bare 'except'
```

the problem is this notebook: https://github.com/ploomber/sql/blob/main/course-material/intro-to-sql/making-your-first-query.md


```
try:
    %pip install jupysql --upgrade duckdb-engine pandas --quiet
    print("Success")
except:
    print("retry installing")

```

having `except:` is not passing the linting. you can fix it with `except Exception:`, but there's no need to have a try except statement there, I'd just put the `%pip install`

**Comment by lfunderburk** [comment]
Checks pass now

**Comment by lfunderburk** [comment]
I think if we merge this PR to main, then merge main to https://github.com/ploomber/sql/pull/17 that should fix the issues 17 is getting

**Pull request merged**
