### PR TITLE
Set up initial Jupyter book with course structure

### PR DESCRIPTION
**Pull request by lfunderburk**
Solves [https://github.com/ploomber/sql/issues/1](https://github.com/ploomber/sql/issues/1)

### CODE REVIEW

**Comment by lfunderburk** [comment]
Hi @edublancas 

This PR looks insane because I created a course structure and built the jupyter book

**Comment by lfunderburk** [comment]
The notebooks don't have content yet- so this can be changed easily

**Comment by lfunderburk** [comment]
Course structure

# From zero to hero: end to end data applications with SQL and Python

## Course structure

### Intro to SQL

1. Connecting to database engines
2. Making your first query
3. Aggregate functions in SQL
4. Joining data in SQL
5. Combining data from multiple tables 

### Interactive queries and parameterization

1. Introduction to `ipywidgets`
2. Parameterize your SQL queries
3. Make your queries interactive

### Advanced querying techniques

1. Writing subqueries
2. Advanced joins
3. Advanced aggregations

### Visualizing your SQL queries

1. Types of data visualizations
2. What makes a visualization good
3. Plotting with `matplotlib`
4. Plotting with `seaborn`
5. Plotting with `plotly`
6. SQL query visualization with `ggplot`

### Data case study: exploratory data analysis

TBD

### Packaging your SQL project

1. How to structure your SQL project
2. Storing credentials securely
3. Introduction to `sqlalchemy`
4. Write SQL utils files
5. Creating an ETL pipeline
6. Running your pipeline
7. Packaging your pipeline

### Introduction to dashboards and apps

1. Introduction to Voila dashboards
2. Writing serverless apps with PyScript

### Deploying your SQL application

1. How to deploy your SQL applications
2. Automating your deployments
3. How to monitor your deployments

**Comment by edublancas** [comment]
please add `doc/_build` to your gitignore, the HTML files should not be included in the repo.

then open a new PR

this might  be helpful: https://stackoverflow.com/a/1139797/709975

**Pull request closed without merging**
