### PR TITLE
Adding Recommender

### PR DESCRIPTION
**Pull request by jpjon**
## Describe your changes
Created `recommender.ipynb`, which contains two different content-based recommendation systems.

One refers to only the "overview" of the movie, while the other refers to both the "overview" and "genre" of the movie.

## Issue number

Closes #

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)

----
:books: Documentation preview :books:: https://ploomber-sql--95.org.readthedocs.build/en/95/

### CODE REVIEW

**Comment by jpjon** [comment]
Hi @lfunderburk. Facing a lot of linting errors (as you can see from my commit history). 

There's something buggy about running `pkgmt` on my end. Can you please run `pkgmt format` and `pkgmt lint` so the PR passes the checks?

**Review by lfunderburk — CHANGES_REQUESTED** [review]
This is a good start, application works as expected

Modifications:

1. Create a recommender_helper.py file with the functions you created
2. Package lose Python code into the recommender_helper.py file
3. Add docstrings to the functions
4. Add a narrative for how the recommender system works
5. How is the genre+overview column different?

**Comment by jpjon** [comment]
Hi @lfunderburk 

I've addressed some of your comments, mainly the ones regarding creating a helper `.py` file and describing the difference of the genre+overview column.

I'll create a short description soon of how the recommender works, but I first wanted your input of the current state of the notebook. If you'd like, I can try to push some more functions into the `.py` helper file (functions such as vectorization and getting the cosine similarity). 

Also, I'm not entirely sure of how to go about of measuring the success/failure of the recommendation. I'm thinking of maybe comparing it to TMDB's recommendation of the movie and seeing if our system has similar recommended movies. I'd like to check by comparing movie watcher's historical preferences, but I don't think TMDB provides tihs data.

**Comment by lfunderburk** [comment]
Hi @jpjon 

Can you do a bit of research/exploration in your code of the following?

Evaluation:

- **Train/Test Split:** You could use user interactions with movies (e.g., ratings, watch history) to create a train-test split. Train the model on a subset of the user interactions and test its performance on the rest.
- **Precision@k:** For the top k recommendations, how many were actually interacted with (or liked) by the users?
- **Recall@k:** Out of the movies that were interacted with (or liked), how many were in the top k recommendations?
- **Mean Average Precision (MAP):** This is an average of the precision scores at every possible rank in the recommendations list and provides a single number evaluation of the recommendation list.
- **Hit Rate:** Whether or not a recommended item was interacted with.
- **Ranking Metrics:** Measures like Normalized Discounted Cumulative Gain (NDCG) consider both the hit and the rank of the hit, discounting hits that appear further down the recommendation list.
- **Coverage:** This measures how many different movies the system recommends across all users. A higher coverage means the system is recommending a wider variety of movies.

Tuning and Optimization:

You might consider tweaking the parameters of TfidfVectorizer such as max_df, min_df, max_features, and the use of custom tokenizers or stop words.
Explore other similarity metrics or even other vectorization techniques.

**Comment by jpjon** [comment]
Hi @lfunderburk 

The requested changes have been implemented. Please let me know if there's anything you'd like to tweak

**Comment by lfunderburk** [comment]
Looks good!

Thank you @jpjon

**Review by lfunderburk — APPROVED** [review]
ready for merge

**Pull request merged**
