### PR TITLE
setting up etl

### PR DESCRIPTION
**Pull request by lfunderburk**
## Describe your changes
Setting up script for data extraction

## Issue number

Closes #X

## Checklist before requesting a review

- [x] Performed a self-review of my code
- [x] Formatted my code with [`pkgmt format`](https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting)

----
:books: Documentation preview :books:: https://ploomber-sql--98.org.readthedocs.build/en/98/

### CODE REVIEW

**Comment by lfunderburk** [comment]
Hi @jpjon 

Can you please give this a read and let me know if the flow is clear, the challenges are reasonable, and if I did a good job of conveying the workflow?

**Comment by jpjon** [comment]
The module is clear and concise. 

The only feedback I have is that when I scroll all the way down from the Poetry section, the "Next" hyperlink does not go to the Designing a Movie Recommender System Pipeline section. 

Also, when I'm on the Poetry section, the table of contents bar to the left does not contain the Designing a Movie Recommender System Pipeline section

**Comment by lfunderburk** [comment]
I had to rebuild the docs a few times before the menu updates

> The only feedback I have is that when I scroll all the way down from the Poetry section, the "Next" hyperlink does not go to the Designing a Movie Recommender System Pipeline section.

What does it direct you to?

**Comment by jpjon** [comment]
It directs me to the Cloud-based options for deployment of applications section

**Comment by lfunderburk** [comment]
are you able to open index.html and visit the "Designing a Movie Recommender System Pipeline" page?

**Comment by jpjon** [comment]
Yup, I'm able to visit that page.

**Pull request merged**
