### PR TITLE
Making basic queries

### PR DESCRIPTION
**Pull request by jpjon**
Resolved - https://github.com/ploomber/sql/issues/7

### CODE REVIEW

**Comment by jpjon** [comment]
Is there a way to show the outputs of the code blocks as well when rendering the .md file?

Other than that, the code is ready for review.

**Comment by edublancas** [comment]
yes, check this out: https://ploomber-contributing.readthedocs.io/en/latest/documentation/notebooks.html

**Review by lfunderburk — CHANGES_REQUESTED** [review]
This is a fantastic start @jpjon!

Very well put together. 

The only suggestion I have is to add a conclusion to the key topics and functions you introduced and talk about how this topic will tie to the next tutorial. Briefly pitch the topics explored in the next tutorial to give continuity.

**Comment by jpjon** [comment]
I've added a conclusion that includes a transition to the next section. 

I also slightly changed the YAML configurations at the top of the file in order to show the outputs of code cells.

One small thing: on line 281, I can't seem to have "Question 3" navigate to Question 3 on the HTML web page when clicked.

**Review by jpjon — COMMENTED** [review]
Got it. A conclusion with a transition will be added soon for clarity.

**Comment by jpjon** [comment]
I've added a conclusion that includes a transition to the next section. 

I also slightly changed the YAML configurations at the top of the file in order to show the outputs of code cells.

One small thing: on line 281, I can't seem to have "Question 3" navigate to Question 3 on the HTML web page when clicked.

Also, my most recent commit does not seem to be showing up on my end on this PR. It went through on my fork and the correct branch origin. If you can not see the most recent commit, please let me know and I can try figuring it out.

**Review by lfunderburk — APPROVED** [review]
This looks great!
Awesome work

**Pull request merged**
